export const CREATE_ITEM_IN_LIST = 'CREATE_ITEM_IN_LIST';

export const SWITCH_FORM_VISIBILITY_FOR_ITEM = 'SWITCH_FORM_VISIBILITY_FOR_ITEM';

export const UPDATE_TEXT_OF_ITEM = 'UPDATE_TEXT_OF_ITEM';

export const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';
