const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';

const SWITCH_FORM_VISIBILITY_FOR_ITEM = 'SWITCH_FORM_VISIBILITY_FOR_ITEM';

const UPDATE_ITEM = 'UPDATE_ITEM';

const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';

export { ADD_ITEM_TO_LIST, SWITCH_FORM_VISIBILITY_FOR_ITEM, UPDATE_ITEM, DELETE_ITEM_FROM_LIST };
