const CREATE_ITEM_IN_LIST = 'CREATE_ITEM_IN_LIST';

const SWITCH_FORM_VISIBILITY_FOR_ITEM = 'SWITCH_FORM_VISIBILITY_FOR_ITEM';

const UPDATE_TEXT_OF_ITEM = 'UPDATE_TEXT_OF_ITEM';

const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';

export { CREATE_ITEM_IN_LIST, SWITCH_FORM_VISIBILITY_FOR_ITEM, UPDATE_TEXT_OF_ITEM, DELETE_ITEM_FROM_LIST };
