export const CREATE_ITEM_IN_LIST: string = 'CREATE_ITEM_IN_LIST';

export const SWITCH_FORM_VISIBILITY_FOR_ITEM: string = 'SWITCH_FORM_VISIBILITY_FOR_ITEM';

export const UPDATE_TEXT_OF_ITEM: string = 'UPDATE_TEXT_OF_ITEM';

export const DELETE_ITEM_FROM_LIST: string = 'DELETE_ITEM_FROM_LIST';

export const FETCH_ITEMS_REQUEST: string = 'FETCH_ITEMS_REQUEST';

export const FETCH_ITEMS_SUCCESS: string = 'FETCH_ITEMS_SUCCESS';

export const FETCH_ITEMS_FAILURE: string = 'FETCH_ITEMS_FAILURE';

export const SEND_ITEM_SUCCESS: string = 'SEND_ITEM_SUCCESS';

export const SEND_ITEM_FAILURE: string = 'SEND_ITEM_FAILURE';
