export const CREATE_ITEM_IN_LIST: string = 'CREATE_ITEM_IN_LIST';

export const SWITCH_FORM_VISIBILITY_FOR_ITEM: string = 'SWITCH_FORM_VISIBILITY_FOR_ITEM';

export const UPDATE_TEXT_OF_ITEM: string = 'UPDATE_TEXT_OF_ITEM';

export const DELETE_ITEM_FROM_LIST: string = 'DELETE_ITEM_FROM_LIST';
