export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_DELETE = 'ITEM_DELETE';
export const ITEM_UPDATE_DESCRIPTION = 'ITEM_UPDATE_DESCRIPTION';
export const ITEM_UPDATE_IS_EDITED = 'ITEM_UPDATE_IS_EDITED';

