const ITEM_CREATED = "ITEM_CREATED";
const ITEM_DELETED = "ITEM_DELETED";
const ITEM_EDITED = "ITEM_EDITED";
const ITEM_EDIT_MODE_TOGGLE = "ITEM_EDIT_MODE_TOGGLE";

export { ITEM_CREATED, ITEM_DELETED, ITEM_EDITED, ITEM_EDIT_MODE_TOGGLE };
