export const ITEM_CHANGE_CANCELLED = 'ITEM_CHANGE_CANCELLED';
export const ITEM_MAKE_EDITABLE = 'ITEM_MAKE_EDITABLE';

export const FETCH_STARTED = 'FETCH_STARTED';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const PUT_REQUEST_STARTED = 'PUT_REQUEST_STARTED';
export const PUT_REQUEST_SUCCESS = 'PUT_REQUEST_SUCCESS';
export const PUT_REQUEST_FAIL = 'PUT_REQUEST_FAIL';

export const POST_REQUEST_STARTED = 'POST_REQUEST_STARTED';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_FAIL = 'POST_REQUEST_FAIL';

export const DELETE_REQUEST_STARTED = 'DELETE_REQUEST_STARTED';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAIL = 'DELETE_REQUEST_FAIL';

export const PARSE_RESPONSE_FINISHED = 'PARSE_RESPONSE_FINISHED';
export const PARSE_RESPONSE_STARTED = 'PARSE_RESPONSE_START';
