export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_DELETE = 'ITEM_DELETE';
export const ITEM_UPDATE_DESCRIPTION = 'ITEM_UPDATE_DESCRIPTION';
export const ITEM_CANCEL_EDITION = 'ITEM_CANCEL_EDITION';
export const ITEM_STORE_EDITED_DESCRIPTION = 'ITEM_STORE_EDITED_DESCRIPTION';
export const ALL_ITEMS_DESCRIPTION_UPDATE = 'ALL_ITEMS_DESCRIPTION_UPDATE';

