export const ITEM_CREATED = 'ITEM_CREATED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_CHANGE_CANCELLED = 'ITEM_CHANGE_CANCELLED';
export const ITEM_CHANGE_SAVED = 'ITEM_CHANGE_SAVED';
export const ITEM_MAKE_EDITABLE = 'ITEM_MAKE_EDITABLE';
